- name: FTP deploy with lftp
  run: |
    sudo apt-get update && sudo apt-get install -y lftp
    lftp -c "open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}; ls"
